import Head from 'next/head';
import Image from 'next/image';

export default function Home(): React.ReactElement {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex min-h-screen justify-center items-center">
          <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
            <img
              className="w-full"
              src="https://tailwindcss.com/img/card-top.jpg"
              alt="Sunset in the mountains"
            />
            <div className="px-6 py-4">
              <h1 className="text-3xl font-bold underline text-teal-500 mb-4">
                Next JS boilerplate + Tailwind!
              </h1>
              <p className="text-grey-darker text-base flex justify-center items-center p-4">
                This is a Next JS boilerplate with Typescript, Tailwind, eslint,
                Prettier, Babel, PWA , Google Analytics, storybook.
              </p>
            </div>
          </div>
        </div>
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
