/** @jsxImportSource theme-ui */
import Head from 'next/head';
import Image from 'next/image';
import { Box } from 'theme-ui'

import styles from '../styles/Home.module.css'

export default function Home(): React.ReactElement {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div sx={{ variant: 'containers.page' }}>
          <h1>Main</h1>
        </div>

        <Box p={4} color="white" bg="primary">
          <div sx={{ variant: 'containers.page', color: 'secondary', border: '1px solid black', padding: '10px' }}>
            Beep
          </div>
        </Box>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}


